//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetProject_Jashim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Books_Title { get; set; }
        public string Books_Image { get; set; }
        public string Books_Pdf { get; set; }
        public string Books_Video { get; set; }
        public string Books_Author_Name { get; set; }
        public string Books_Isbn { get; set; }
        public string available_Quantity { get; set; }
    }
}
