//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetProject_Jashim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Books
    {
        public int Id { get; set; }
        public string Student_Enrollment_No { get; set; }
        public string Books_Isbn { get; set; }
        public string Books_Issue_Date { get; set; }
        public string Books_Approx_Return_Date { get; set; }
        public string Student_UserName { get; set; }
        public string Is_Book_Returned { get; set; }
        public string Book_Returned_Date { get; set; }
    }
}
